version: '2'
services:
  redis:
    image: redis:alpine
  web: 
    build: .
    volumes:
      - .:/lunchbot
    tty: true
    env_file:
      - .env
    command: sh -c 'bundle exec rerun rackup -- --host 0.0.0.0'
    ports:
      - '9292:9292'
    links:
      - redis
  worker:
    image: lunchbot_web
    volumes:
      - .:/lunchbot
    tty: true
    env_file:
      - .env
    command: sh -c 'bundle exec rerun sidekiq -- -r ./app/app.rb'
    links:
      - redis
