version: '2'
services:
  redis:
    image: redis:alpine
  web:
    build: .
    volumes:
      - .:/lunchbot
    working_dir: /lunchbot
    tty: true
    command: sh -c 'source .env && bundle exec rerun rackup -- --host 0.0.0.0'
    ports:
      - '9292:9292'
    links:
      - redis
