version: '2'
services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - '80:80'
      - '443:443'
    labels:
      traefik.enable: 'false'

  redis:
    image: redis:alpine
    labels:
      traefik.enable: 'false'

  web: 
    build: .
    volumes:
      - .:/lunchbot
    tty: true
    env_file:
      - .env
    command: sh -c 'bundle exec rake db:migrate && bundle exec rerun rackup -- --host 0.0.0.0'
    depends_on:
      - redis
    labels:
      traefik.backend: 'lunchbot-web'
      traefik.frontend.rule: 'Host:lunchbot.net'
      traefik.enable: 'true'
      traefik.port: 9292

  worker:
    image: lunchbot_web
    volumes:
      - .:/lunchbot
    tty: true
    env_file:
      - .env
    command: sh -c 'bundle exec rerun sidekiq -- -r ./app/app.rb'
    depends_on:
      - redis
    labels:
      traefik.enable: 'false'
